import { useState } from 'react'

// ── GitHub API helpers ────────────────────────────────────────────────────────
const ghFetch = (url, token, options = {}) =>
  fetch(`https://api.github.com${url}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

const b64 = (str) => btoa(unescape(encodeURIComponent(str)))

// ── Push files to GitHub ──────────────────────────────────────────────────────
async function pushToGitHub({ token, repoName, html, appName, description, schemas, intent }) {
  // 1. Get authenticated user
  const meRes = await ghFetch('/user', token)
  if (!meRes.ok) throw new Error('Invalid GitHub token. Make sure it has "repo" scope.')
  const me = await meRes.json()
  const owner = me.login

  // 2. Create repo (ignore if already exists)
  const createRes = await ghFetch('/user/repos', token, {
    method: 'POST',
    body: JSON.stringify({
      name: repoName,
      description: `Generated by AI App Compiler — ${description}`,
      private: false,
      auto_init: false,
    }),
  })
  // 422 = already exists, that's fine
  if (!createRes.ok && createRes.status !== 422) {
    const err = await createRes.json()
    throw new Error(err.message || 'Could not create repository')
  }

  // Wait a moment for repo to initialise
  await new Promise(r => setTimeout(r, 1200))

  // 3. Build file contents
  const readme = `# ${appName}

> Generated by [AI App Compiler](https://github.com) — ${description}

## 🚀 Quick Start

### Option A — Open directly in browser
\`\`\`
Just double-click index.html
\`\`\`

### Option B — Deploy to Netlify in 10 seconds
1. Go to [app.netlify.com/drop](https://app.netlify.com/drop)
2. Drag & drop \`index.html\`
3. Done ✅

### Option C — GitHub Pages
1. Go to repo **Settings → Pages**
2. Source: **Deploy from a branch → main → / (root)**
3. Your app is live at \`https://${owner}.github.io/${repoName}\`

## 📋 App Details

| Field | Value |
|---|---|
| App Type | ${intent?.app_type || 'Web App'} |
| Complexity | ${intent?.complexity || 'medium'} |
| Roles | ${(intent?.user_roles || []).join(', ')} |
| Features | ${(intent?.core_features || []).slice(0, 4).join(', ')} |

## 🏗️ Tech Stack
- **Frontend**: React 18 (CDN, no build step)
- **Styling**: Inline CSS-in-JS
- **Database**: Browser LocalStorage
- **Auth**: Role-based (${(schemas?.auth_schema?.roles || []).join(', ')})
- **Generated**: ${new Date().toISOString().split('T')[0]}

---
*Built with AI App Compiler*
`

  const schemasJson = JSON.stringify({
    ui_schema: schemas?.ui_schema,
    api_schema: schemas?.api_schema,
    db_schema: schemas?.db_schema,
    auth_schema: schemas?.auth_schema,
  }, null, 2)

  const files = [
    { path: 'index.html',   content: html },
    { path: 'README.md',    content: readme },
    { path: 'schemas.json', content: schemasJson },
  ]

  // 4. Push each file
  for (const file of files) {
    // Check if file exists (to get its sha for update)
    let sha = null
    try {
      const existing = await ghFetch(`/repos/${owner}/${repoName}/contents/${file.path}`, token)
      if (existing.ok) {
        const data = await existing.json()
        sha = data.sha
      }
    } catch (_) {}

    const body = {
      message: sha ? `Update ${file.path} via AI App Compiler` : `Add ${file.path} via AI App Compiler`,
      content: b64(file.content),
      ...(sha ? { sha } : {}),
    }

    const res = await ghFetch(`/repos/${owner}/${repoName}/contents/${file.path}`, token, {
      method: 'PUT',
      body: JSON.stringify(body),
    })
    if (!res.ok) {
      const err = await res.json()
      throw new Error(`Failed to push ${file.path}: ${err.message}`)
    }
  }

  return {
    repoUrl: `https://github.com/${owner}/${repoName}`,
    pagesUrl: `https://${owner}.github.io/${repoName}`,
    owner,
  }
}

// ── GitHub Push Modal ─────────────────────────────────────────────────────────
export default function GitHubPushModal({ onClose, html, appName, description, schemas, intent }) {
  const safeName = (appName || 'my-app').toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')

  const [token,   setToken]   = useState('')
  const [repo,    setRepo]    = useState(safeName)
  const [status,  setStatus]  = useState('idle') // idle | pushing | done | error
  const [result,  setResult]  = useState(null)
  const [error,   setError]   = useState('')
  const [showToken, setShowToken] = useState(false)

  const push = async () => {
    if (!token.trim()) { setError('Please enter your GitHub token.'); return }
    if (!repo.trim())  { setError('Please enter a repository name.'); return }
    setStatus('pushing')
    setError('')
    try {
      const res = await pushToGitHub({ token, repoName: repo, html, appName, description, schemas, intent })
      setResult(res)
      setStatus('done')
    } catch (e) {
      setError(e.message)
      setStatus('error')
    }
  }

  const s = {
    overlay: { position:'fixed', inset:0, background:'rgba(0,0,0,0.8)', display:'flex', alignItems:'center', justifyContent:'center', zIndex:2000, backdropFilter:'blur(4px)' },
    modal:   { background:'#0d1117', border:'1px solid #1f2937', borderRadius:20, padding:32, width:520, maxWidth:'95vw', boxShadow:'0 24px 80px rgba(0,0,0,0.7)' },
    label:   { fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.06em', color:'#64748b', marginBottom:6, display:'block' },
    input:   { width:'100%', background:'#111827', border:'1px solid #1f2937', borderRadius:8, padding:'10px 12px', color:'#f1f5f9', fontSize:13, outline:'none', marginBottom:16 },
    btn:     (v) => ({ padding:'10px 20px', borderRadius:8, border:'none', cursor:'pointer', fontSize:13, fontWeight:600,
                background: v==='primary' ? 'linear-gradient(135deg,#6366f1,#7c3aed)' : v==='ghost' ? 'transparent' : '#1f2937',
                color:'#fff', boxShadow: v==='primary' ? '0 2px 20px rgba(99,102,241,0.4)' : 'none' }),
  }

  return (
    <div style={s.overlay} onClick={e => e.target === e.currentTarget && onClose()}>
      <div style={s.modal}>

        {/* Header */}
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:24 }}>
          <div>
            <div style={{ fontSize:20, fontWeight:700, color:'#f1f5f9', display:'flex', alignItems:'center', gap:10 }}>
              <span style={{ fontSize:24 }}>🐙</span> Push to GitHub
            </div>
            <div style={{ fontSize:12, color:'#64748b', marginTop:4 }}>
              Your generated app will be pushed as a GitHub repository
            </div>
          </div>
          <button onClick={onClose} style={{ background:'none', border:'none', color:'#64748b', fontSize:22, cursor:'pointer' }}>✕</button>
        </div>

        {status !== 'done' ? (
          <>
            {/* Token field */}
            <label style={s.label}>
              GitHub Personal Access Token
              <a href="https://github.com/settings/tokens/new?scopes=repo&description=AI+App+Compiler"
                target="_blank" rel="noreferrer"
                style={{ marginLeft:8, fontSize:11, color:'#6366f1', textDecoration:'none', fontWeight:400, textTransform:'none', letterSpacing:0 }}>
                + Create one ↗
              </a>
            </label>
            <div style={{ position:'relative', marginBottom:16 }}>
              <input
                type={showToken ? 'text' : 'password'}
                placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                value={token}
                onChange={e => setToken(e.target.value)}
                style={{ ...s.input, marginBottom:0, paddingRight:44 }}
              />
              <button onClick={() => setShowToken(v => !v)}
                style={{ position:'absolute', right:10, top:'50%', transform:'translateY(-50%)', background:'none', border:'none', color:'#64748b', cursor:'pointer', fontSize:14 }}>
                {showToken ? '🙈' : '👁️'}
              </button>
            </div>

            {/* Tip box */}
            <div style={{ background:'rgba(99,102,241,0.06)', border:'1px solid rgba(99,102,241,0.2)', borderRadius:8, padding:'10px 14px', fontSize:12, color:'#94a3b8', marginBottom:16, lineHeight:1.6 }}>
              💡 Create a token at <strong style={{color:'#818cf8'}}>GitHub → Settings → Developer Settings → Personal Access Tokens → Fine-grained</strong>.
              Enable <code style={{background:'rgba(245,158,11,0.1)',color:'#f59e0b',padding:'1px 5px',borderRadius:4}}>Contents: Read & Write</code> permission.
            </div>

            {/* Repo name */}
            <label style={s.label}>Repository Name</label>
            <input
              type="text"
              placeholder={safeName}
              value={repo}
              onChange={e => setRepo(e.target.value.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,''))}
              style={s.input}
            />

            {/* What gets pushed */}
            <div style={{ background:'#111827', border:'1px solid #1f2937', borderRadius:10, padding:'12px 16px', marginBottom:20 }}>
              <div style={{ fontSize:12, fontWeight:700, color:'#94a3b8', marginBottom:10 }}>📁 Files that will be created:</div>
              {[
                { name:'index.html', desc:'Complete self-contained React app (open in browser = works!)' },
                { name:'README.md',  desc:'Auto-generated docs with deploy instructions' },
                { name:'schemas.json', desc:'Full UI, API, DB & Auth JSON schemas' },
              ].map(f => (
                <div key={f.name} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'6px 0', borderBottom:'1px solid #1f2937' }}>
                  <code style={{ fontSize:12, color:'#f59e0b', background:'rgba(245,158,11,0.1)', padding:'2px 6px', borderRadius:4, flexShrink:0 }}>{f.name}</code>
                  <span style={{ fontSize:12, color:'#64748b' }}>{f.desc}</span>
                </div>
              ))}
            </div>

            {/* Error */}
            {error && (
              <div style={{ background:'rgba(239,68,68,0.1)', border:'1px solid rgba(239,68,68,0.3)', borderRadius:8, padding:'10px 14px', color:'#fca5a5', fontSize:12, marginBottom:16 }}>
                ⚠️ {error}
              </div>
            )}

            {/* Buttons */}
            <div style={{ display:'flex', gap:10 }}>
              <button onClick={push} disabled={status==='pushing'} style={{ ...s.btn('primary'), flex:1, opacity: status==='pushing' ? 0.7 : 1 }}>
                {status === 'pushing' ? '⏳ Pushing to GitHub…' : '🐙 Push to GitHub'}
              </button>
              <button onClick={onClose} style={s.btn('ghost')}>Cancel</button>
            </div>
          </>
        ) : (
          /* ── Success State ─────────────────────────────── */
          <div>
            <div style={{ textAlign:'center', padding:'8px 0 24px' }}>
              <div style={{ fontSize:52, marginBottom:12 }}>🎉</div>
              <div style={{ fontSize:20, fontWeight:700, color:'#f1f5f9', marginBottom:8 }}>Successfully Pushed!</div>
              <div style={{ fontSize:13, color:'#64748b' }}>Your app is now on GitHub and ready to deploy</div>
            </div>

            {[
              { label:'🐙 GitHub Repository', url: result.repoUrl, desc:'View source code, README, schemas', color:'#818cf8' },
              { label:'🌐 GitHub Pages URL',  url: result.pagesUrl, desc:'Enable in Settings → Pages to go live', color:'#34d399' },
            ].map(item => (
              <div key={item.url} style={{ background:'#111827', border:'1px solid #1f2937', borderRadius:10, padding:'14px 16px', marginBottom:12 }}>
                <div style={{ fontSize:12, fontWeight:700, color: item.color, marginBottom:6 }}>{item.label}</div>
                <a href={item.url} target="_blank" rel="noreferrer"
                  style={{ fontSize:13, color:'#f1f5f9', textDecoration:'none', wordBreak:'break-all' }}>
                  {item.url} ↗
                </a>
                <div style={{ fontSize:11, color:'#475569', marginTop:4 }}>{item.desc}</div>
              </div>
            ))}

            <div style={{ background:'rgba(16,185,129,0.06)', border:'1px solid rgba(16,185,129,0.2)', borderRadius:8, padding:'10px 14px', fontSize:12, color:'#94a3b8', marginTop:4, lineHeight:1.6 }}>
              💡 <strong style={{color:'#34d399'}}>Enable GitHub Pages:</strong> Go to your repo → Settings → Pages → Source: Deploy from branch → main → / (root) → Save.
              Your app goes live at the URL above in ~30 seconds!
            </div>

            <button onClick={onClose} style={{ ...s.btn('primary'), width:'100%', marginTop:20 }}>Done ✓</button>
          </div>
        )}
      </div>
    </div>
  )
}
